name: artifact-push
description: Push docker image workflow artifacts to ghcr
inputs:
  GITHUB_TOKEN:
    description: Token for accessing ghcr. Set to github.token. Omit to disable docker login.
    required: false
runs:
  using: composite
  steps:
    - name: Download images
      uses: actions/github-script@v6.4.1
      with:
        # language=javascript
        script: |
          var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || github.run_id }},
          });
          var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "docker-images"
          })[0];
          var download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          var fs = require('fs');
          fs.writeFileSync('${{github.workspace}}/docker-images.zip', Buffer.from(download.data));
    - run: unzip docker-images.zip
      shell: bash
    - name: prepare ghcr.io login
      if: ${{ inputs.GITHUB_TOKEN != '' }}
      run: echo 'skopeo login -u "${{ github.repository_owner }}" -p "${{ inputs.GITHUB_TOKEN }}" ghcr.io' >> entrypoint.sh
      shell: bash
    - name: prepare upload script
      #language=bash
      run: |
        for image in $(cat docker-images.txt); do
          echo "skopeo copy oci-archive:/image.tar:$(echo $image | cut -d: -f2) docker://$image" >> entrypoint.sh
        done
        chmod +x entrypoint.sh
      shell: bash
    - name: push all images
      run: > 
        docker run --rm
        -v "$(pwd)/image.tar:/image.tar:ro"
        -v "$(pwd)/entrypoint.sh:/entrypoint.sh:ro"
        --entrypoint /bin/bash
        quay.io/skopeo/stable:v1.14.0
        /entrypoint.sh
      shell: bash
